local DamageTypes = {
	Health = {
		Corpus = {
			Color = "228, 35%",
			CSSTextColorClass = "var(--faction-corpus-text-color)",
			DarkModeColor = "#6f87e8",
			Faction = { "Corpus" },
			InternalName = "RK_CORPUS_FACTION",
			Introduced = "36",
			Link = "Damage/Corpus",
            Name = "Corpus",
			Type = "Health" 
		},
		["Corpus Amalgam"] = {
			Color = "238, 25%",
			CSSTextColorClass = "var(--faction-corpus-amalgam-text-color)",
			DarkModeColor = "#8c90ec",
			Faction = { "Corpus Amalgam" },
			InternalName = "RK_CORPUS_AMALGAM_FACTION",
			Introduced = "36",
			Link = "Damage/Corpus Amalgam",
            Name = "Corpus Amalgam",
			Type = "Health" 
		},
		Grineer = {
			Color = "90, 5%",
			CSSTextColorClass = "var(--faction-grineer-text-color)",
			DarkModeColor = "#9cbb76",
			Faction = { "Grineer" },
			InternalName = "RK_GRINEER_FACTION",
			Introduced = "36",
			Link = "Damage/Grineer",
            Name = "Grineer",
			Type = "Health" 
		},
		Infested = {
			Color = "180, 5%",
			CSSTextColorClass = "var(--faction-infested-text-color)",
			DarkModeColor = "#9db9b9",
			Faction = { "Infested" },
			InternalName = "RK_INFESTED_FACTION",
			Introduced = "36",
			Link = "Damage/Infested",
            Name = "Infested",
			Type = "Health" 
		},
		["Infested Deimos"] = {
			Color = "310, 14%",
			CSSTextColorClass = "var(--faction-infested-deimos-text-color)",
			DarkModeColor = "#f093b9",
			Faction = { "Infested Deimos" },
			InternalName = "RK_INFESTED_DEIMOS_FACTION",
			Introduced = "36",
			Link = "Damage/Infested Deimos",
            Name = "Infested Deimos",
			Type = "Health" 
		},
		["Kuva Grineer"] = {
			Color = "30, 5%",
			CSSTextColorClass = "var(--faction-kuva-grineer-text-color)",
			DarkModeColor = "#e66261",
			Faction = { "Kuva Grineer" },
			InternalName = "RK_GRINEER_KUVA_FACTION",
			Introduced = "36",
			Link = "Damage/Kuva Grineer",
            Name = "Kuva Grineer",
			Type = "Health" 
		},
		Narmer = {
			Color = "40, 30%",
			CSSTextColorClass = "var(--faction-narmer-text-color)",
			DarkModeColor = "#d3a954",
			Faction = { "Narmer" },
			InternalName = "RK_NARMER_FACTION",
			Introduced = "36",
			Link = "Damage/Narmer",
            Name = "Narmer",
			Type = "Health" 
		},
		Object = {
			Color = "90, 0%",
			CSSTextColorClass = "var(--faction-object-text-color)",
			DarkModeColor = "#bbb",
			Faction = { "" },
			InternalName = "RK_NEUTRAL",
			Link = "Damage/Object",
			Name = "Object",
			Nickname = "Object",
			Type = "Health" 
		},
		Orokin = {
			Color = "55, 30%",
			CSSTextColorClass = "var(--faction-orokin-text-color)",
			DarkModeColor = "#d5c94b",
			Faction = { "Orokin" },
			InternalName = "RK_OROKIN_FACTION",
			Introduced = "36",
			Link = "Damage/Orokin",
            Name = "Orokin",
			Type = "Health" 
		},
		Overguard = {
			Color = "228, 51%",
			CSSTextColorClass = "var(--faction-overguard-text-color)",
			DarkModeColor = "#c6cadb",
			Faction = { "Grineer", "Corpus", "Infested", "The Murmur" },
			Icon = "Overguard.png",
			InternalName = "",
			Introduced = "31.5",
			Link = "Overguard",
			Name = "Overguard",
			Type = "Health",
			Status = { "Prevents status effects and damage spillover to Shields and Health", "Enemy crowd control immunity" } 
		},
		Sentient = {
			Color = "26, 31%",
			CSSTextColorClass = "var(--faction-sentient-text-color)",
			DarkModeColor = "#d58e58",
			Faction = { "Sentient" },
			InternalName = "RK_SENTIENT_FACTION",
			Introduced = "36",
			Link = "Damage/Sentient",
            Name = "Sentient",
			Type = "Health" 
		},
		Tenno = {
			Color = "250, 10%",
			CSSTextColorClass = "var(--faction-tenno-text-color)",
			DarkModeColor = "#9f89ff",
			Faction = { "Tenno" },
			InternalName = "RK_TENNO_FACTION",
			Introduced = "36",
			Link = "Damage/Tenno",
            Name = "Tenno",
			Type = "Health" 
		},
		["The Murmur"] = {
			Color = "153, 2%",
			CSSTextColorClass = "var(--faction-the-murmur-text-color)",
			DarkModeColor = "#a7bfb6",
			Faction = { "The Murmur" },
			InternalName = "RK_MITW_FACTION",
			Introduced = "35.5",
			Link = "Damage/The Murmur",
            Name = "The Murmur",
			Type = "Health" 
		},
		Zariman = {
			Color = "153, 10%",
			CSSTextColorClass = "var(--faction-zariman-text-color)",
			DarkModeColor = "#97b7a9",
			Faction = { "Zariman" },
			InternalName = "RK_ZARIMAN_FACTION",
			Introduced = "36",
			Link = "Damage/Zariman",
            Name = "Zariman",
			Type = "Health" 
		},
		Scaldra = {
			Color = "153, 20%",
			CSSTextColorClass = "var(--faction-scaldra-text-color)",
			DarkModeColor = "#81c4a7",
			Faction = { "Scaldra" },
			InternalName = "RK_LASRIA_FACTION",
			Introduced = "38",
			Link = "Damage/Scaldra",
            Name = "Scaldra",
			Type = "Health" 
		},
		Techrot = {
			Color = "153, 10%",
			CSSTextColorClass = "var(--faction-techrot-text-color)",
			DarkModeColor = "#97bbac",
			Faction = { "Techrot" },
			InternalName = "RK_PROTOINFESTED_FACTION",
			Introduced = "38",
			Link = "Damage/Techrot",
            Name = "Techrot",
			Type = "Health" 
		},
		Anarchs = {
			Color = "153, 10%",
			CSSTextColorClass = "var(--faction-anarch-text-color)",
			DarkModeColor = "#97bbac",
			Faction = { "Anarchs" },
			InternalName = "RK_OROKIN_EMPIRE_FACTION",
			Introduced = "41",
			Link = "Damage/Anarchs",
            Name = "Anarchs",
			Type = "Health" 
		},
		["Tenno Armor"] = {
			Color = "60, 5%",
			DarkModeColor = "#c2c25e",
			Faction = { "Tenno" },
			InternalName = "RK_TENNO_ARMOR",
			Link = "Tenno Armor",
			Name = "Tenno Armor",
			Type = "Armor" 
		},
		["Tenno Flesh"] = {
			Color = "0, 85%",
			DarkModeColor = "#c67676",
			Faction = { "Tenno" },
			InternalName = "RK_TENNO_FLESH",
			Link = "Tenno Flesh",
			Name = "Tenno Flesh",
			Type = "Health" 
		},
		["Tenno Shield"] = {
			Color = "228, 51%",
			DarkModeColor = "#a3afdd",
			Faction = { "Tenno" },
			InternalName = "RK_TENNO_SHIELD",
			Link = "Tenno Shield",
			Name = "Tenno Shield",
			Type = "Shield" 
		},
		--- Depreciated health/armor types as of U36; keeping to preserve links and template calls on wiki
		["Alloy Armor"] = {
			Bypass = { "Cinematic", "True" },
			Color = "90, 5%",
			DarkModeColor = "#a2b788",
			Faction = { "Grineer" },
			InternalName = "RK_HULKING_ARMOR",
			Introduced = "11",
			Link = "Alloy Armor",
			Name = "Alloy Armor",
			Negatives = { { "Electricity", 50 }, { "Magnetic", 50 } },
			Nickname = "Alloy",
			Positives = { { "Radiation", 75 }, { "Cold", 25 }, { "Puncture", 15 }},
			Type = "Armor" 
		},
		["Cloned Flesh"] = {
			Color = "26, 31%",
			DarkModeColor = "#dfa376",
			Faction = { "Grineer" },
			InternalName = "RK_CLONED_FLESH",
			Introduced = "11",
			Link = "Cloned Flesh",
			Name = "Cloned Flesh",
			Negatives = { { "Gas", 50 }, { "Impact", 25 } },
			Nickname = "Cloned",
			Positives = { { "Viral", 75 }, { "Heat", 25 }, { "Slash", 25 } },
			Type = "Health" 
		},
		["Ferrite Armor"] = {
			Bypass = { "Cinematic", "True" },
			Color = "30, 5%",
			DarkModeColor = "#ceaa7f",
			Faction = { "Grineer" },
			InternalName = "RK_ARMOR",
			Introduced = "11",
			Link = "Ferrite Armor",
			Name = "Ferrite Armor",
			Negatives = { { "Blast", 25 }, { "Slash", 15 } },
			Nickname = "Ferrite",
			Positives = { { "Corrosive", 75 }, { "Puncture", 50 } },
			Type = "Armor" 
		},
		Flesh = {
			Color = "13, 31%",
			DarkModeColor = "#ff987a",
			Faction = { "Corpus" },
			InternalName = "RK_FLESH",
			Introduced = "11",
			Link = "Flesh",
			Name = "Flesh",
			Negatives = { { "Gas", 25 }, { "Impact", 25 } },
			Positives = { { "Viral", 50 }, { "Toxin", 50 }, { "Slash", 25 } },
			Type = "Health" 
		},
		Fossilized = {
			Color = "140, 8%",
			DarkModeColor = "#96bda4",
			Faction = { "Infested" },
			InternalName = "RK_FOSSILIZED",
			Introduced = "11",
			Link = "Fossilized",
			Name = "Fossilized",
			Negatives = { { "Radiation", 75 }, { "Toxin", 50 }, { "Cold", 25 } },
			Nickname = "Fossil",
			Positives = { { "Corrosive", 75 }, { "Blast", 50 }, { "Slash", 15 } },
			Type = "Health" 
		},
		["Infested (Damage 2.0)"]= {
			Color = "180, 5%",
			DarkModeColor = "#9db9b9",
			Faction = { "Infested" },
			InternalName = "RK_INFESTED",
			Introduced = "11",
			Link = "Damage 2.0/Infested",
			Name = "Infested",
			Negatives = { { "Radiation", 50 }, { "Viral", 50 } },
			Positives = { { "Gas", 75 }, { "Heat", 25 }, { "Slash", 25 } },
			Type = "Health" 
		},
		["Infested Flesh"] = {
			Color = "70, 5%",
			DarkModeColor = "#afb39c",
			Faction = { "Infested" },
			InternalName = "RK_INFESTED_FLESH",
			Introduced = "11",
			Link = "Infested Flesh",
			Name = "Infested Flesh",
			Negatives = { { "Cold", 50 } },
			Nickname = "I. Flesh",
			Positives = { { "Gas", 50 }, { "Heat", 50 }, { "Slash", 50 } },
			Type = "Health" 
		},
		["Infested Sinew"] = {
			Bypass = { "Cinematic", "True" },
			Color = "310, 14%",
			DarkModeColor = "#cea2c7",
			Faction = { "Infested" },
			InternalName = "RK_INFESTED_ARMOUR",
			Introduced = "11",
			Link = "Infested Sinew",
			Name = "Infested Sinew",
			Negatives = { { "Blast", 50 } },
			Nickname = "Sinew",
			Positives = { { "Radiation", 50 }, { "Cold", 25 }, { "Puncture", 25 } },
			Type = "Armor" 
		},
		Machinery = {
			Color = "250, 10%",
			DarkModeColor = "#b3acd0",
			Faction = { "Grineer" },
			InternalName = "RK_MACHINERY",
			Introduced = "11",
			Link = "Machinery",
			Name = "Machinery",
			Negatives = { { "Viral", 25 }, { "Toxin", 25 } },
			Nickname = "Machine",
			Positives = { { "Blast", 75 }, { "Electricity", 50 }, { "Impact", 25 } },
			Type = "Health" 
		},
		["Proto Shield"] = {
			Bypass = { "Toxin" },
			Color = "238, 41%",
			DarkModeColor = "#9d9fd9",
			Faction = { "Corpus" },
			InternalName = "RK_HEAVY_SHIELD",
			Introduced = "11",
			Link = "Proto Shield",
			Name = "Proto Shield",
			Negatives = { { "Corrosive", 50 }, { "Heat", 50 }, { "Puncture", 50 } },
			Nickname = "Proto",
			Positives = { { "Magnetic", 75 }, { "Toxin", 25 },  { "Impact", 15 } },
			Type = "Shield" 
		},
		Robotic = {
			Color = "220, 25%",
			DarkModeColor = "#86afff",
			Faction = { "Corpus" },
			InternalName = "RK_ROBOTIC",
			Introduced = "11",
			Link = "Robotic (Health)",
			Name = "Robotic",
			Negatives = { { "Toxin", 25 }, { "Slash", 25 } },
			Positives = { { "Radiation", 25 }, { "Electricity", 50 }, { "Puncture", 25 } },
			Type = "Health" 
		},
		Shield = {
			Bypass = { "Toxin" },
			Color = "228, 51%",
			DarkModeColor = "#a2aedf",
			Faction = { "Corpus" },
			InternalName = "RK_SHIELD",
			Introduced = "11",
			Link = "Shield (Health)",
			Name = "Shield",
			Negatives = { { "Puncture", 20 } },	-- TODO: Not 25%?
			Positives = { { "Magnetic", 75 }, { "Cold", 50 }, { "Impact", 50 } },
			Type = "Shield" 
		},
		["Indifferent Facade"] = {
			Color = "153, 2%",
			Faction = { "The Murmur"},
			InternalName = "",
			Introduced = "35.5",
			Link = "Indifferent Facade",
			Name = "Indifferent Facade",
			Negatives = { { "Viral", 50 }, { "Slash", 50 } },
			Nickname = "Facade",
			Positives = { { "Radiation", 75 }, { "Void", 25 }, { "Electricity", 25 }, { "Puncture", 25 } },
			Type = "Health" 
		},
	},
	Notes = {
		[1] = "Does not affect Bosses.",
		[2] = "Does not affect Rollers, Regulators, Latchers or Ospreys.",
		[3] = "Does not affect MOAs.",
		[4] = "This Status Effect bypasses Shield protections as it consists of Toxin damage.",
		[5] = "The damage associated bypasses these secondary protections." 
	},
	Procs = {
		["Big Stagger"] = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "MeleeStagger_d.png",
			InternalName = "PT_BIG_STAGGER",
			Link = "Stagger",
			Name = "Big Stagger",
			Status = { "Longer stagger effect" }
		},
		Blind = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "RadialBlind130xDark.png",
			Link = "Blind",
			Name = "Blind",
			Status = { "Enemy is in a blinded state, opening them up to front/back finishers" }
		},
		Freeze = {
			Color = "#17658c",
			ColorBackground = "#c3d5df",
			ColorBorder = "#1c638d",
			CSSBackgroundColorClass = "var(--dt-cold-background-color)",
			CSSBorderColorClass = "var(--dt-cold-border-color)",
			CSSTextColorClass = "var(--dt-cold-text-color)",
			DarkModeColor = "#5bbcec",
			GlyphImage = "ColdModBundleIcon.png",
			Icon = "DmgColdSmall64.png",
			InternalName = "PT_CHILLED",
			Link = "Damage/Cold Damage",
			Name = "Freeze",
			Status = { "Slower movement and attack speed" } 
		},
		["Corrosion"] = {
			Color = "#4d6600",
			ColorBackground = "#d8dfc3",
			ColorBorder = "#708d1c",
			CSSBackgroundColorClass = "var(--dt-corrosive-background-color)",
			CSSBorderColorClass = "var(--dt-corrosive-border-color)",
			CSSTextColorClass = "var(--dt-corrosive-text-color)",
			DarkModeColor = "#93c203",
			GlyphImage = "EssentialCorrosiveGlyph.png",
			Icon = "DmgCorrosiveSmall64.png",
			InternalName = "PT_CAUSTIC_BURN",
			Link = "Damage/Corrosive Damage",
			Name = "Corrosion",
			Status = { "Armor reduction" }
		},
		Concuss = {
			Color = "#3d5e5e",
			ColorBackground = "#cad8d8",
			ColorBorder = "#486061",
			DarkModeColor = "#80c4c4",
			CSSBackgroundColorClass = "var(--dt-impact-background-color)",
			CSSBorderColorClass = "var(--dt-impact-border-color)",
			CSSTextColorClass = "var(--dt-impact-text-color)",
			GlyphImage = "EssentialImpactGlyph.png",
			Icon = "DmgImpactSmall64.png",
			InternalName = "",
			IsRailjack = true,
			Link = "Damage/Impact Damage#Railjack",
			Name = "Concuss",
			Status = { "Enemy crew have reduced accuracy and damage" },
			StatusNotes = { 1, 2 } 
		},
		["Tesla Chain"] = {
			Color = "#610fb3",
			ColorBackground = "#d2c3df",
			ColorBorder = "#561c8d",
			CSSBackgroundColorClass = "var(--dt-electricity-background-color)",
			CSSBorderColorClass = "var(--dt-electricity-border-color)",
			CSSTextColorClass = "var(--dt-electricity-text-color)",
			DarkModeColor = "#c4a2e6",
			GlyphImage = "ElectricModBundleIcon.png",
			Icon = "DmgElectricitySmall64.png",
			InternalName = "PT_ELECTROCUTION",
			Link = "Damage/Electricity Damage",
			Name = "Tesla Chain",
			Status = { "Tesla Chain", "Stun", "Electric DoT as Electricity damage" },
			StatusNotes = { 1, 2 } 
		},
		Disarmed = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "RadialDisarm.png",
			InternalName = "PT_DISARMED",
			Link = "Disarm",
			Name = "Disarmed",
			Status = { "Equipped weapon is disarmed" }
		},
		Decompress = {
			Color = "#5c5247",
			ColorBackground = "#d8d1ca",
			ColorBorder = "#615448",
			DarkModeColor = "#c6b098",
			CSSBackgroundColorClass = "var(--dt-puncture-background-color)",
			CSSBorderColorClass = "var(--dt-puncture-border-color)",
			CSSTextColorClass = "var(--dt-puncture-text-color)",
			GlyphImage = "EssentialPunctureGlyph.png",
			Icon = "DmgPunctureSmall64.png",
			InternalName = "",
			IsRailjack = true,
			Link = "Damage/Puncture Damage#Railjack",
			Name = "Decompress",
			Status = { "Reduce target ship's Shields and Armor" } 
		},
		Detonate = {
			Color = "#b32a00",
			ColorBackground = "#dfcac3",
			ColorBorder = "#8d361c",
			CSSBackgroundColorClass = "var(--dt-blast-background-color)",
			CSSBorderColorClass = "var(--dt-blast-border-color)",
			CSSTextColorClass = "var(--dt-blast-text-color)",
			DarkModeColor = "#dd704e",
			Icon = "DmgBlastSmall64.png",
			InternalName = "",
			Link = "Damage/Blast Damage",
			Name = "Detonate",
			Status = { "Mini explosion" }
		},
		Inaccuracy = {
			Color = "#b32a00",
			ColorBackground = "#dfcac3",
			ColorBorder = "#8d361c",
			CSSBackgroundColorClass = "var(--dt-blast-background-color)",
			CSSBorderColorClass = "var(--dt-blast-border-color)",
			CSSTextColorClass = "var(--dt-blast-text-color)",
			DarkModeColor = "#dd704e",
			Icon = "DmgBlastSmall64.png",
			InternalName = "PT_FLASHBANG",
			Link = "Damage 2.0/Blast Damage",
			Name = "Inaccuracy",
			Status = { "Accuracy reduction" }
		},
		Intoxicate = {
			Color = "#061",
			ColorBackground = "#c3dfc8",
			ColorBorder = "#1c8d30",
			DarkModeColor = "#0c2",
			CSSBackgroundColorClass = "var(--dt-toxin-background-color)",
			CSSBorderColorClass = "var(--dt-toxin-border-color)",
			CSSTextColorClass = "var(--dt-toxin-text-color)",
			GlyphImage = "ToxinModBundleIcon.png",
			Icon = "DmgToxinSmall64.png",
			InternalName = "",
			IsRailjack = true,
			Link = "Damage/Toxin Damage#Railjack",
			Name = "Intoxicate",
			Status = { "Change Faction of afflicted target", "Enable friendly fire" } 
		},
		Immobilize = {
			Color = "#17658c",
			ColorBackground = "#c3d5df",
			ColorBorder = "#1c638d",
			CSSBackgroundColorClass = "var(--dt-cold-background-color)",
			CSSBorderColorClass = "var(--dt-cold-border-color)",
			CSSTextColorClass = "var(--dt-cold-text-color)",
			DarkModeColor = "#5bbcec",
			GlyphImage = "ColdModBundleIcon.png",
			Icon = "DmgColdSmall64.png",
			InternalName = "",
			IsRailjack = true,
			Link = "Damage/Cold Damage#Railjack",
			Name = "Immobilize",
			Status = { "Disable ship weaponry", "Slow ship movement to complete stop", "Ice Hazard on Railjack", "Disables interactive elements in Railjack" } 
		},
		["Gas Cloud"] = {
			Color = "#063",
			ColorBackground = "#c3dfd2",
			ColorBorder = "#1c8d5a",
			DarkModeColor = "#0c6",
			CSSBackgroundColorClass = "var(--dt-gas-background-color)",
			CSSBorderColorClass = "var(--dt-gas-border-color)",
			CSSTextColorClass = "var(--dt-gas-text-color)",
			GlyphImage = "EssentialGasGlyph.png",
			Icon = "DmgGasSmall64.png",
			InternalName = "PT_ASPHYXIATION",
			Link = "Damage/Gas Damage",
			Name = "Gas Cloud",
			Status = { "Gas Cloud that deals DoT as Gas damage" },
		},
		Ignite = {
			Color = "#994d00",
			ColorBackground = "#dfd0c3",
			ColorBorder = "#8d501c",
			DarkModeColor = "#fb9733",
			CSSBackgroundColorClass = "var(--dt-heat-background-color)",
			CSSBorderColorClass = "var(--dt-heat-border-color)",
			CSSTextColorClass = "var(--dt-heat-text-color)",
			GlyphImage = "HeatModBundleIcon.png",
			Icon = "DmgFireSmall64.png",
			InternalName = "PT_IMMOLATION",
			Link = "Damage/Heat Damage",
			Name = "Ignite",
			Status = { "Fire DoT as Heat damage", "Panic", "Armor reduction" },
			StatusNotes = { 1, 2, 3 } 
		},
		Knockback = {
			Color = "#3d5e5e",
			ColorBackground = "#cad8d8",
			ColorBorder = "#486061",
			DarkModeColor = "#80c4c4",
			CSSBackgroundColorClass = "var(--dt-impact-background-color)",
			CSSBorderColorClass = "var(--dt-impact-border-color)",
			CSSTextColorClass = "var(--dt-impact-text-color)",
			GlyphImage = "EssentialImpactGlyph.png",
			Icon = "DmgImpactSmall64.png",
			InternalName = "PT_KNOCKBACK",
			Link = "Damage/Impact Damage",
			Name = "Knockback",
			Status = { "Stagger", "Increased health threshold for Mercy finisher" },
			StatusNotes = { 1, 2 } 
		},
		Disrupt = {
			Color = "#4747d1",
			ColorBackground = "#c4c3df",
			ColorBorder = "#201c8d",
			DarkModeColor = "#9797e6",
			CSSBackgroundColorClass = "var(--dt-magnetic-background-color)",
			CSSBorderColorClass = "var(--dt-magnetic-border-color)",
			CSSTextColorClass = "var(--dt-magnetic-text-color)",
			GlyphImage = "EssentialMagneticGlyph.png",
			Icon = "DmgMagneticSmall64.png",
			InternalName = "PT_MAGNETIZED",
			Link = "Damage/Magnetic Damage",
			Name = "Disrupt",
			Status = { "Additional damage against Shields and Overguard", "Delays natural shield regeneration", "Electricity DoT on Shield/Overguard break" }
		},
		Impair = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "DmgImpairSmall64.png",
			InternalName = "PT_ROOTS",
			Link = "Impair",
			Name = "Impair",
			Status = { "Disables jumping, bullet jump, and sprinting" }
		},
		Knockdown = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "Knockdown_b.png",
			InternalName = "PT_KNOCKED_DOWN",
			Link = "Knockdown",
			Name = "Knockdown",
			Status = { "Knock down enemy, opening them up to ground finishers" }
		},
		Lifted = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "Lifted_b.png",
			InternalName = "PT_LIFT_HIT",
			Link = "Lifted",
			Name = "Lifted",
			Status = { "Immobilized in mid-air" }
		},
		Microwave = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "Nukor.png",
			InternalName = "PT_MICROWAVE_BURN",
			Link = "Microwave",
			Name = "Microwave",
			Status = { "Enlarged body parts" }
		},
		Parried = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "UnidentifiedItem.png",
			InternalName = "PT_PARRIED",
			Link = "Parry",
			Name = "Parried",
			Status = { "Opens enemy up to a counter-finisher" }
		},
		["PT_VOID"] = {
			Color = "#ff0000",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#15c8ab",
			Icon = "UnidentifiedItem.png",
			InternalName = "PT_VOID",
			Link = "WARFRAME Wiki",
			Name = "PT_VOID",
			Status = { "Unknown; may be old version of bullet attractor (PT_RADIANT)" }
		},
		Ragdoll = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "Ragdoll b.png",
			InternalName = "PT_RAGDOLL",
			Link = "Ragdoll",
			Name = "Ragdoll",
			Status = { "Ragdolls the enemy" }
		},
		Scramble = {
			Color = "#610fb3",
			ColorBackground = "#d2c3df",
			ColorBorder = "#561c8d",
			CSSBackgroundColorClass = "var(--dt-electricity-background-color)",
			CSSBorderColorClass = "var(--dt-electricity-border-color)",
			CSSTextColorClass = "var(--dt-electricity-text-color)",
			DarkModeColor = "#c4a2e6",
			GlyphImage = "ElectricModBundleIcon.png",
			Icon = "DmgElectricitySmall64.png",
			InternalName = "",
			IsRailjack = true,
			Link = "Damage/Electricity Damage#Railjack",
			Name = "Scramble",
			Status = { "Disable enemy weaponry", "Spiral enemy ship out of control", "Electricity Hazard on Railjack", "Scrambles minimap", "Disable Tactical Menu" },
			StatusNotes = { } 
		},
		Sear = {
			Color = "#994d00",
			ColorBackground = "#dfd0c3",
			ColorBorder = "#8d501c",
			DarkModeColor = "#fb9733",
			CSSBackgroundColorClass = "var(--dt-heat-background-color)",
			CSSBorderColorClass = "var(--dt-heat-border-color)",
			CSSTextColorClass = "var(--dt-heat-text-color)",
			GlyphImage = "HeatModBundleIcon.png",
			Icon = "DmgFireSmall64.png",
			InternalName = "",
			IsRailjack = true,
			Link = "Damage/Heat Damage#Railjack",
			Name = "Sear",
			Status = { "Fire DoT as Heat damage", "Fire Hazard on Railjack", "Railjack Armaments overheat faster and cool slower" },
			StatusNotes = { } 
		},
		Silence = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "Silence130xDark.png",
			InternalName = "PT_SILENCED",
			Link = "Silence",
			Name = "Silence",
			Status = { "Deafens the enemy and disables most active abilities" }
		},
		Sleep = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "RestRage130xDark.png",
			InternalName = "PT_SLEEP",
			Link = "Sleep",
			Name = "Sleep",
			Status = { "Puts enemy to sleep, preserving their alert state and opening them to finishers" }
		},
		-- Unsure if PT_GLUE is associated with "Slow"
		Slow = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "WebbedEmbrace.png",
			InternalName = "PT_GLUE",
			Link = "Slow",
			Name = "Slow",
			Status = { "Slows the enemy" }
		},
		Stagger = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "MeleeStagger_d.png",
			InternalName = "PT_STAGGERED",
			Link = "Stagger",
			Name = "Stagger",
			Status = { "Staggers the enemy, interrupting many actions" }
		},
		Stun = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "StunIcon_b.png",
			InternalName = "PT_STUNNED",
			Link = "Stagger",
			Name = "Stun",
			Status = { "Stuns the enemy, interrupting many actions for a time" }
		},
		Tear = {
			Color = "#7a5254",
			ColorBackground = "#d8cacb",
			ColorBorder = "#614849",
			DarkModeColor = "#e69ca0",
			CSSBackgroundColorClass = "var(--dt-slash-background-color)",
			CSSBorderColorClass = "var(--dt-slash-border-color)",
			CSSTextColorClass = "var(--dt-slash-text-color)",
			GlyphImage = "EssentialSlashGlyph.png",
			Icon = "DmgSlashSmall64.png",
			InternalName = "",
			IsRailjack = true,
			Link = "Damage/Slash Damage#Railjack",
			Name = "Tear",
			Status = { "Increase damage vulnerability on target" } 
		},
		Weakened = {
			Color = "#5c5247",
			ColorBackground = "#d8d1ca",
			ColorBorder = "#615448",
			DarkModeColor = "#c6b098",
			CSSBackgroundColorClass = "var(--dt-puncture-background-color)",
			CSSBorderColorClass = "var(--dt-puncture-border-color)",
			CSSTextColorClass = "var(--dt-puncture-text-color)",
			GlyphImage = "EssentialPunctureGlyph.png",
			Icon = "DmgPunctureSmall64.png",
			InternalName = "PT_FRAILTY",
			Link = "Damage/Puncture Damage",
			Name = "Weakened",
			Status = { "Target deals reduced damage" } 
		},
		Confusion = {
			Color = "#806000",
			ColorBackground = "#dfd8c3",
			ColorBorder = "#8d701c",
			DarkModeColor = "#dda600",
			CSSBackgroundColorClass = "var(--dt-radiation-background-color)",
			CSSBorderColorClass = "var(--dt-radiation-border-color)",
			CSSTextColorClass = "var(--dt-radiation-text-color)",
			GlyphImage = "EssentialRadiationGlyph.png",
			Icon = "DmgRadiationSmall64.png",
			InternalName = "PT_RAD_TOX",
			Link = "Damage/Radiation Damage",
			Name = "Confusion",
			Status = { "Friendly fire" },
			StatusNotes = { 1 }
		},
		Bleed = {
			Color = "#7a5254",
			ColorBackground = "#d8cacb",
			ColorBorder = "#614849",
			DarkModeColor = "#e69ca0",
			CSSBackgroundColorClass = "var(--dt-slash-background-color)",
			CSSBorderColorClass = "var(--dt-slash-border-color)",
			CSSTextColorClass = "var(--dt-slash-text-color)",
			GlyphImage = "EssentialSlashGlyph.png",
			Icon = "DmgSlashSmall64.png",
			InternalName = "PT_BLEEDING",
			Link = "Damage/Slash Damage",
			Name = "Bleed",
			Status = { "Bleed DoT as True damage" } 
		},
		Poison = {
			Bypass = { "Tenno Shield" },
			BypassNotes = { 5 },
			Color = "#061",
			ColorBackground = "#c3dfc8",
			ColorBorder = "#1c8d30",
			DarkModeColor = "#0c2",
			CSSBackgroundColorClass = "var(--dt-toxin-background-color)",
			CSSBorderColorClass = "var(--dt-toxin-border-color)",
			CSSTextColorClass = "var(--dt-toxin-text-color)",
			GlyphImage = "ToxinModBundleIcon.png",
			Icon = "DmgToxinSmall64.png",
			InternalName = "PT_POISONED",
			Link = "Damage/Toxin Damage",
			Name = "Poison",
			Status = { "Poison DoT as Toxin damage" } 
		},
		Virus = {
			Color = "#b71658",
			ColorBackground = "#dfc3cf",
			ColorBorder = "#8d1c4b",
			DarkModeColor = "#f093b9",
			CSSBackgroundColorClass = "var(--dt-viral-background-color)",
			CSSBorderColorClass = "var(--dt-viral-border-color)",
			CSSTextColorClass = "var(--dt-viral-text-color)",
			GlyphImage = "EssentialViralGlyph.png",
			Icon = "DmgViralSmall64.png",
			InternalName = "PT_INFECTED",
			Link = "Damage/Viral Damage",
			Name = "Virus",
			Status = { "Increased damage against Health" }
		},
		["Status Vulnerability"] = {
			Color = "#b30000",
			ColorBackground = "#dfc3c4",
			ColorBorder = "#8d1c1f",
			DarkModeColor = "#f06666",
			CSSBackgroundColorClass = "var(--dt-tau-background-color)",
			CSSBorderColorClass = "var(--dt-tau-border-color)",
			CSSTextColorClass = "var(--dt-tau-text-color)",
			GlyphImage = "EssentialTauGlyph.png",
			Icon = "DmgTauSmall64.png",
			InternalName = "PT_SENTIENT",
			Link = "Damage/Tau Damage",
			Name = "Status Vulnerability",
			Status = { "Increased likelihood of Status procs on target" }
		},
		["Bullet Attractor"] = {
			Color = "#085e50",
			ColorBackground = "#c3dfd9",
			ColorBorder = "#1c8d76",
			DarkModeColor = "#15c8ab",
			CSSBackgroundColorClass = "var(--dt-void-background-color)",
			CSSBorderColorClass = "var(--dt-void-border-color)",
			CSSTextColorClass = "var(--dt-void-text-color)",
			GlyphImage = "EssentialVoidGlyph.png",
			Icon = "DmgVoidSmall64.png",
			InternalName = "PT_RADIANT",
			Link = "Damage/Void Damage",
			Name = "Bullet Attractor",
			Status = { "Spawn a bullet attraction field on target" }
		} 
	},
	Types = {
		Blast = {
			Color = "#b32a00",
			ColorBackground = "#dfcac3",
			ColorBorder = "#8d361c",
			CSSBackgroundColorClass = "var(--dt-blast-background-color)",
			CSSBorderColorClass = "var(--dt-blast-border-color)",
			CSSTextColorClass = "var(--dt-blast-text-color)",
			DarkModeColor = "#dd704e",
			GlyphImage = "EssentialBlastGlyph.png",
			Icon = "DmgBlastSmall64.png",
			InternalName = "DT_EXPLOSION",
			Link = "Damage/Blast Damage",
			Name = "Blast",
			Negatives = { "Corpus Amalgam", "Tenno Shield" },
			Positives = { "Infested Deimos" },
			ProcInternalName = "",
			Status = { "Mini Explosion" },
			Types = { "Heat", "Cold" } 
		},
		Cinematic = {
			Bypass = { "Tenno Armor" },
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "UnidentifiedItem.png",
			InternalName = "DT_CINEMATIC",
			Link = "Damage/Cinematic Damage",
			Name = "Cinematic",
			Negative = {},
			Positives = {},
		},
		Cold = {
			Color = "#17658c",
			ColorBackground = "#c3d5df",
			ColorBorder = "#1c638d",
			CSSBackgroundColorClass = "var(--dt-cold-background-color)",
			CSSBorderColorClass = "var(--dt-cold-border-color)",
			CSSTextColorClass = "var(--dt-cold-text-color)",
			DarkModeColor = "#5bbcec",
			GlyphImage = "ColdModBundleIcon.png",
			Icon = "DmgColdSmall64.png",
			InternalName = "DT_FREEZE",
			Link = "Damage/Cold Damage",
			Name = "Cold",
			Negatives = { "Tenno Shield", "Techrot" },
			Positives = { "Sentient" },
			ProcInternalName = "PT_CHILLED",
			Status = { "Slowdown", "Crit Damage +" } 
		},
		Corrosive = {
			Color = "#4d6600",
			ColorBackground = "#d8dfc3",
			ColorBorder = "#708d1c",
			CSSBackgroundColorClass = "var(--dt-corrosive-background-color)",
			CSSBorderColorClass = "var(--dt-corrosive-border-color)",
			CSSTextColorClass = "var(--dt-corrosive-text-color)",
			DarkModeColor = "#93c203",
			GlyphImage = "EssentialCorrosiveGlyph.png",
			Icon = "DmgCorrosiveSmall64.png",
			InternalName = "DT_CORROSIVE",
			Link = "Damage/Corrosive Damage",
			Name = "Corrosive",
			Negatives = { "Sentient", "Tenno Shield" },
			Positives = { "Grineer", "Kuva Grineer", "Scaldra" },
			ProcInternalName = "PT_CAUSTIC_BURN",
			Status = { "Armor Reduction" },
			Types = { "Electricity", "Toxin" } 
		},
		Electricity = {
			Color = "#610fb3",
			ColorBackground = "#d2c3df",
			ColorBorder = "#561c8d",
			CSSBackgroundColorClass = "var(--dt-electricity-background-color)",
			CSSBorderColorClass = "var(--dt-electricity-border-color)",
			CSSTextColorClass = "var(--dt-electricity-text-color)",
			DarkModeColor = "#b37fe7",
			GlyphImage = "ElectricModBundleIcon.png",
			Icon = "DmgElectricitySmall64.png",
			InternalName = "DT_ELECTRICITY",
			Link = "Damage/Electricity Damage",
			Name = "Electricity",
			Negatives = { "Tenno Shield" },
			Positives = { "Corpus Amalgam", "The Murmur", "Anarchs" },
			ProcInternalName = "PT_ELECTROCUTION",
			Status = { "Tesla Chain DoT", "Stun" },
			StatusNotes = { 1, 2 } 
		},
		["Energy Drain"] = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "DisrupterAncientDE.png",
			InternalName = "DT_ENERGY_DRAIN",
			Link = "Damage/Energy Drain",
			Name = "Energy Drain"
		},
		Finisher = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "Finisher_b.png",
			Link = "Finisher",
			Name = "Finisher" 
		},
		Gas = {
			Color = "#063",
			ColorBackground = "#c3dfd2",
			ColorBorder = "#1c8d5a",
			CSSBackgroundColorClass = "var(--dt-gas-background-color)",
			CSSBorderColorClass = "var(--dt-gas-border-color)",
			CSSTextColorClass = "var(--dt-gas-text-color)",
			DarkModeColor = "#0c6",
			GlyphImage = "EssentialGasGlyph.png",
			Icon = "DmgGasSmall64.png",
			InternalName = "DT_GAS",
			Link = "Damage/Gas Damage",
			Name = "Gas",
			Negatives = { "Tenno Shield", "Scaldra" },
			Positives = { "Infested Deimos", "Techrot" },
			ProcInternalName = "PT_ASPHYXIATION",
			Status = { "Gas Cloud DoT" },
			Types = { "Heat", "Toxin" } 
		},
		Heat = {
			Color = "#994d00",
			ColorBackground = "#dfd0c3",
			ColorBorder = "#8d501c",
			CSSBackgroundColorClass = "var(--dt-heat-background-color)",
			CSSBorderColorClass = "var(--dt-heat-border-color)",
			CSSTextColorClass = "var(--dt-heat-text-color)",
			DarkModeColor = "#fb9733",
			GlyphImage = "HeatModBundleIcon.png",
			Icon = "DmgFireSmall64.png",
			InternalName = "DT_FIRE",
			Link = "Damage/Heat Damage",
			Name = "Heat",
			Negatives = { "Kuva Grineer", "Tenno Shield" },
			Positives = { "Infested" },
			ProcInternalName = "PT_IMMOLATION",
			Status = { "Ignite DoT", "Panic", "Armor Reduction" },
			StatusNotes = { 1, 2, 3 } 
		},
		Impact = {
			Color = "#3d5e5e",
			ColorBackground = "#cad8d8",
			ColorBorder = "#486061",
			CSSBackgroundColorClass = "var(--dt-impact-background-color)",
			CSSBorderColorClass = "var(--dt-impact-border-color)",
			CSSTextColorClass = "var(--dt-impact-text-color)",
			DarkModeColor = "#80c4c4",
			GlyphImage = "EssentialImpactGlyph.png",
			Icon = "DmgImpactSmall64.png",
			InternalName = "DT_IMPACT",
			Link = "Damage/Impact Damage",
			Name = "Impact",
			Negatives = { "Tenno Shield" },
			Positives = { "Grineer", "Kuva Grineer", "Scaldra", "Anarchs" },
			ProcInternalName = "PT_KNOCKBACK",
			Status = { "Stagger", "Mercy Kill Chance +" },
			StatusNotes = { 1, 2 } 
		},
		Magnetic = {
			Color = "#4747d1",
			ColorBackground = "#c4c3df",
			ColorBorder = "#201c8d",
			CSSBackgroundColorClass = "var(--dt-magnetic-background-color)",
			CSSBorderColorClass = "var(--dt-magnetic-border-color)",
			CSSTextColorClass = "var(--dt-magnetic-text-color)",
			DarkModeColor = "#9797e6",
			GlyphImage = "EssentialMagneticGlyph.png",
			Icon = "DmgMagneticSmall64.png",
			InternalName = "DT_MAGNETIC",
			Link = "Damage/Magnetic Damage",
			Name = "Magnetic",
			Negatives = { "Narmer", "Tenno Shield" },
			Positives = { "Corpus", "Corpus Amalgam", "Techrot" },
			ProcInternalName = "PT_MAGNETIZED",
			Status = { "Additional Shield and Overguard Damage", "Electricity DoT on Shield/Overguard break" },
			Types = { "Cold", "Electricity" } 
		},
		Puncture = {
			Color = "#5c5247",
			ColorBackground = "#d8d1ca",
			ColorBorder = "#615448",
			CSSBackgroundColorClass = "var(--dt-puncture-background-color)",
			CSSBorderColorClass = "var(--dt-puncture-border-color)",
			CSSTextColorClass = "var(--dt-puncture-text-color)",
			DarkModeColor = "#c6b098",
			GlyphImage = "EssentialPunctureGlyph.png",
			Icon = "DmgPunctureSmall64.png",
			InternalName = "DT_PUNCTURE",
			Link = "Damage/Puncture Damage",
			Name = "Puncture",
			Negatives = { "Tenno Shield" },
			Positives = { "Corpus", "Orokin" },
			ProcInternalName = "PT_FRAILTY",
			Status = { "Weakened", "Crit Chance +" } 
		},
		Radiation = {
			Color = "#806000",
			ColorBackground = "#dfd8c3",
			ColorBorder = "#8d701c",
			CSSBackgroundColorClass = "var(--dt-radiation-background-color)",
			CSSBorderColorClass = "var(--dt-radiation-border-color)",
			CSSTextColorClass = "var(--dt-radiation-text-color)",
			DarkModeColor = "#ceac49",
			GlyphImage = "EssentialRadiationGlyph.png",
			Icon = "DmgRadiationSmall64.png",
			InternalName = "DT_RADIATION",
			Link = "Damage/Radiation Damage",
			Name = "Radiation",
			Negatives = { "Orokin", "Tenno Shield", "Anarchs" },
			Positives = { "Sentient", "The Murmur" },
			ProcInternalName = "PT_RAD_TOX",
			Status = { "Friendly Fire" },
			StatusNotes = { 1 },
			Types = { "Heat", "Electricity" } 
		},
		["Shield Drain"] = {
			Color = "#5d5d5d",
			CSSBackgroundColorClass = "var(--dt-default-background-color)",
			CSSBorderColorClass = "var(--dt-default-border-color)",
			CSSTextColorClass = "var(--dt-default-text-color)",
			DarkModeColor = "#d5d5d5",
			Icon = "IconShield.png",
			InternalName = "DT_SHIELD_DRAIN",
			Link = "Damage/Shield Drain",
			Name = "Shield Drain",
			Negative = {},
			Positives = {},
		},
		Slash = {
			Color = "#7a5254",
			ColorBackground = "#d8cacb",
			ColorBorder = "#614849",
			CSSBackgroundColorClass = "var(--dt-slash-background-color)",
			CSSBorderColorClass = "var(--dt-slash-border-color)",
			CSSTextColorClass = "var(--dt-slash-text-color)",
			DarkModeColor = "#e69ca0",
			GlyphImage = "EssentialSlashGlyph.png",
			Icon = "DmgSlashSmall64.png",
			InternalName = "DT_SLASH",
			Link = "Damage/Slash Damage",
			Name = "Slash",
			Negatives = { "Tenno Shield" },
			Positives = { "Infested", "Narmer" },
			ProcInternalName = "PT_BLEEDING",
			Status = { "Bleed DoT" } 
		},
		Tau = {
			Color = "#b30000",
			ColorBackground = "#dfc3c4",
			ColorBorder = "#8d1c1f",
			CSSBackgroundColorClass = "var(--dt-tau-background-color)",
			CSSBorderColorClass = "var(--dt-tau-border-color)",
			CSSTextColorClass = "var(--dt-tau-text-color)",
			DarkModeColor = "#f06666",
			GlyphImage = "EssentialTauGlyph.png",
			Icon = "DmgTauSmall64.png",
			InternalName = "PT_SENTIENT",
			Link = "Damage/Tau Damage",
			Name = "Tau",
			Negatives = { "Tenno Shield" },
			Status = { "Status Vulnerability" } 
		},
		Toxin = {
			Bypass = { "Tenno Shield" },
			BypassNotes = { 5 },
			Color = "#061",
			ColorBackground = "#c3dfc8",
			ColorBorder = "#1c8d30",
			CSSBackgroundColorClass = "var(--dt-toxin-background-color)",
			CSSBorderColorClass = "var(--dt-toxin-border-color)",
			CSSTextColorClass = "var(--dt-toxin-text-color)",
			DarkModeColor = "#0c2",
			GlyphImage = "ToxinModBundleIcon.png",
			Icon = "DmgToxinSmall64.png",
			InternalName = "DT_POISON",
			Link = "Damage/Toxin Damage",
			Name = "Toxin",
			Negatives = { "Tenno Shield" },
			Positives = { "Narmer" },
			ProcInternalName = "PT_POISONED",
			Status = { "Poison DoT" } 
		},
		True = {
			Bypass = { "Tenno Armor" },
			BypassNotes = { 5 },
			Color = "#664d00",
			ColorBackground = "#ddd6c7",
			ColorBorder = "#d8a12b",
			CSSBackgroundColorClass = "var(--dt-true-background-color)",
			CSSBorderColorClass = "var(--dt-true-border-color)",
			CSSTextColorClass = "var(--dt-true-text-color)",
			DarkModeColor = "#dda700",
			GlyphImage = "EssentialTrueGlyph.png",
			Icon = "DmgTrueSmall64.png",
			InternalName = "DT_FINISHER",
			Link = "Damage/True Damage",
			Name = "True" 
		},
		Viral = {
			Color = "#b71658",
			ColorBackground = "#dfc3cf",
			ColorBorder = "#8d1c4b",
			CSSBackgroundColorClass = "var(--dt-viral-background-color)",
			CSSBorderColorClass = "var(--dt-viral-border-color)",
			CSSTextColorClass = "var(--dt-viral-text-color)",
			DarkModeColor = "#f093b9",
			GlyphImage = "EssentialViralGlyph.png",
			Icon = "DmgViralSmall64.png",
			InternalName = "DT_VIRAL",
			Link = "Damage/Viral Damage",
			Name = "Viral",
			Negatives = { "Infested Deimos", "Tenno Shield", "The Murmur" },
			Positives = { "Orokin" },
			ProcInternalName = "PT_INFECTED",
			Status = { "Increased Health Damage" },
			Types = { "Cold", "Toxin" } 
		},
		Void = {
			Color = "#085e50",
			ColorBackground = "#c3dfd9",
			ColorBorder = "#1c8d76",
			CSSBackgroundColorClass = "var(--dt-void-background-color)",
			CSSBorderColorClass = "var(--dt-void-border-color)",
			CSSTextColorClass = "var(--dt-void-text-color)",
			DarkModeColor = "#15c8ab",
			GlyphImage = "EssentialVoidGlyph.png",
			Icon = "DmgVoidSmall64.png",
			InternalName = "DT_RADIANT",
			Link = "Damage/Void Damage",
			Name = "Void",
			Negatives = { "Tenno Shield" },
			Positives = { "Overguard", "Zariman" },
			ProcInternalName = "PT_RADIANT",
			Status = { "Bullet Attract" } 
		} 
	},
	dictionary = {
		FactionOrder = { "Grineer", "Corpus", "Infested", "The Murmur" },
		Factions = {
			Corpus = { { "Flesh", "Shield", "Proto Shield", "Robotic", "Overguard" }, { "#C8C8FF", "#E8E8FF" } },
			Grineer = {
				{ "Cloned Flesh", "Ferrite Armor", "Alloy Armor", "Machinery", "Overguard" },
				{ "#FFC8C8", "#FFE8E8" } 
			},
			Infested = {
				{ "Infested", "Infested Flesh", "Fossilized", "Infested Sinew", "Overguard" },
				{ "#C8FFC8", "#E8FFE8" } 
			},
			["The Murmur"] = { { "Indifferent Facade", "Overguard"}, { "#B5C7BA", "#4E524F" } },
		},
		Health = {
			{ "Impact", 73 },
			{ "Puncture", 73 },
			{ "Slash", 73 },
			{ "Cold", 78 },
			{ "Electricity", 78 },
			{ "Heat", 78 },
			{ "Toxin", 78 },
			{ "Blast", 83 },
			{ "Corrosive", 83 },
			{ "Gas", 83 },
			{ "Magnetic", 83 },
			{ "Radiation", 83 },
			{ "Viral", 83 },
			{ "True", 88 },
			{ "Void", 88 },
			{ "Tau", 88 } 
		},
		Types = {
			{ "Cloned Flesh", "Grineer" },
			{ "Flesh", "Corpus" },
			{ "Infested", "Infested" },
			{ "Indifferent Facade", "The Murmur" },
			{ "Ferrite Armor", "Grineer" },
			{ "Shield", "Corpus" },
			{ "Infested Flesh", "Infested" },
			{ "Machinery", "The Murmur" },
			{ "Alloy Armor", "Grineer" },
			{ "Proto Shield", "Corpus" },
			{ "Fossilized", "Infested" },
			{ "Ferrite Armor", "The Murmur" },
			{ "Machinery", "Grineer" },
			{ "Robotic", "Corpus" },
			{ "Infested Sinew", "Infested" },
		} 
	},
	total = { ["Tenno Flesh"] = {  } } 
}
--[==[creation script:
for k,v in pairs(p.Health) do print([=[
	["]=]..k..[=["] = {
		Positives = {},] =]..(v.Bypass and '\n		Bypass = {},\n' or '\n')..[=[
		Negatives = {},
		Nickname = "",
		Faction = {""},
		Type = "",
		Color = "",
	},]=]) end
--health type patch creation:
		if not DamageTypes["Health"][v[1]] then
			--error(v[1])
			DamageTypes["Health"][v[1]] = {
				Positives = {},
				Bypass = {},
				Negatives = {},
				Nickname = "Error",
				Faction = {"Grineer", "Corpus", "Infested"},
				Type = "Health",
				Color = "0, 100%",
			}
		end
]==]
--[= =[
for k, t in pairs(DamageTypes["Types"]) do--type name, type
	for c,n in ipairs{'Negatives','Bypass','Positives'} do--positive and negative
		for __,v in ipairs(t[n] or {}) do--each attribute {'health type',#percent}
			if type(v)~='table' then v={v,50} end--default magnitude
			--put patch script here
			if not DamageTypes["Health"][v[1]] then
				error(v[1]) -- health type has no data
			end
			if not DamageTypes["Health"][v[1]][n] then DamageTypes["Health"][v[1]][n] = {} end--init modifier
			table.insert(DamageTypes["Health"][v[1]][n], {k,v[2]})--add attribute {type name, #percent}
			for ___,doh in ipairs{{k,v[1]},{v[1],k}} do--loop between damage and health names
				if not DamageTypes["total"][doh[1]] then DamageTypes["total"][doh[1]] = {} end--init modifier listing
				DamageTypes["total"][doh[1]][doh[2]] = (c-2)*v[2]
				--	  total	  [valname][other one]   +-val
			end
		end
	end
end
local function hslrgb(H,S,L)
	--HSL to RGB converter
	--mostly by u:gigamicro
	--C and m from https://www.rapidtables.com/convert/color/hsl-to-rgb.html
	S,L = S/100, L/100 -- from percentages
	local C = (1-math.abs((2*L)-1))*S--range
	local m = L-(C/2)--minimum

	--where the horizontal axis is H, _ is m, ‾ is C+m, and /\ are linterps
	--r ‾\__/‾
	--g /‾‾\__
	--b __/‾‾\
	local function cycle(H)
		return((
			math.min((
				math.max((
					math.abs((
						((H)/180)
					%2)-1)--triangle wave, period 360
				*3),1)--cut off bottom third
			-1),1)--and top third
		*C)+m)--map to range
	end
	local R,G,B = cycle(H), cycle(H-120), cycle(H+120)

	--hex
	return ('#%.2X%.2X%.2X'):format(
		math.floor(0.00390625 + R * 255),
		math.floor(0.00390625 + G * 255),
		math.floor(0.00390625 + B * 255))
end
for k, t in pairs(DamageTypes["Health"]) do
	--t.Positives, t.Negatives, t.Bypass = t.Positives[1] and t.Positives, t.Negatives[1] and t.Negatives, t.Bypass[1] and t.Bypass -- empty lists -> nil

	local H,S = t.Color:match '^(.+), (.+)%%$' -- grabs numbers from 'num, num%'
	t.Color = hslrgb(H,S,40) -- text
	t.ColorBorder = hslrgb(H,S,50) -- tt border
	t.ColorBackground = hslrgb(H,S,85) -- tt bg (translucent)
end
--]==]
return DamageTypes
